#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudstack-credentials
  namespace: #@ data.values.namespace
type: Opaque
stringData:
  api-url: #@ data.values.cloudstack_api_url
  api-key: #@ data.values.cloudstack_api_key
  secret-key: #@ data.values.cloudstack_secret_key
  verify-ssl: #@ data.values.cloudstack_verify_ssl
