#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudstack-secret
  namespace: kube-system
type: Opaque
stringData:
  cloud-config: #@ "[Global]\napi-url = " + data.values.cloudstack_api_url + "\napi-key = " + data.values.cloudstack_api_key + "\nsecret-key = " + data.values.cloudstack_secret_key + "\nssl-no-verify = " + data.values.cloudstack_verify_ssl + "\n"
