apiVersion: v1
kind: Namespace
metadata:
  name: capc-rke2-cluster-1
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudstack-credentials
  namespace: capc-rke2-cluster-1
type: Opaque
stringData:
  api-url: <CLOUDSTACK_API_URL>
  api-key: <CLOUDSTACK_API_KEY>
  secret-key: <CLOUDSTACK_SECRET_KEY>
  verify-ssl: "false"