apiVersion: v1
kind: Secret
metadata:
  name: cloudstack-credentials
type: Opaque
stringData:
  api-url: "<cloudstack-api-url>"
  api-key: "<api-key>"
  secret-key: "<secret-key>"
  verify-ssl: "false"
